import { urals, s7 } from '../images/avia-company';

const numberOfTicketsOnPage = 3;

const ticketsInfo = [
	{
		price: '4570',
		company: 'Уральские авиалинии',
		image: urals,
		segments: [
			{
				origin: 'Москва',
				originCode: 'DME',
				destination: 'Калининград',
				destinationCode: 'KGD',
				date: '27 мая, сб',
				time: '19:15',
				duration: '2:45',
				dateDest: '27 мая, сб',
				timeDest: '22:45',
			},
			{
				origin: 'Калининград',
				originCode: 'KGD',
				destination: 'Москва',
				destinationCode: 'DME',
				date: '3 июня, сб',
				time: '19:15',
				duration: '2:45',
				dateDest: '3 июня, сб',
				timeDest: '22:45',
			},
		],
	},
	{
		price: '4570',
		company: 'S7 Airlines',
		image: s7,
		segments: [
			{
				origin: 'Москва',
				originCode: 'DME',
				destination: 'Калининград',
				destinationCode: 'KGD',
				date: '27 мая, сб',
				time: '19:15',
				duration: '2:45',
				dateDest: '27 мая, сб',
				timeDest: '22:45',
			},
			{
				origin: 'Калининград',
				originCode: 'KGD',
				destination: 'Москва',
				destinationCode: 'DME',
				date: '3 июня, сб',
				time: '19:15',
				duration: '2:45',
				dateDest: '3 июня, сб',
				timeDest: '22:45',
			},
		],
	},
	{
		price: '4570',
		company: 'Уральские авиалинии',
		image: urals,
		segments: [
			{
				origin: 'Москва',
				originCode: 'DME',
				destination: 'Калининград',
				destinationCode: 'KGD',
				date: '27 мая, сб',
				time: '19:15',
				duration: '2:45',
				dateDest: '27 мая, сб',
				timeDest: '22:45',
			},
			{
				origin: 'Калининград',
				originCode: 'KGD',
				destination: 'Москва',
				destinationCode: 'DME',
				date: '3 июня, сб',
				time: '19:15',
				duration: '2:45',
				dateDest: '3 июня, сб',
				timeDest: '22:45',
			},
		],
	},
	{
		price: '4570',
		company: 'Уральские авиалинии',
		image: urals,
		segments: [
			{
				origin: 'Москва',
				originCode: 'DME',
				destination: 'Калининград',
				destinationCode: 'KGD',
				date: '27 мая, сб',
				time: '19:15',
				duration: '2:45',
				dateDest: '27 мая, сб',
				timeDest: '22:45',
			},
			{
				origin: 'Калининград',
				originCode: 'KGD',
				destination: 'Москва',
				destinationCode: 'DME',
				date: '3 июня, сб',
				time: '19:15',
				duration: '2:45',
				dateDest: '3 июня, сб',
				timeDest: '22:45',
			},
		],
	},
	{
		price: '2000',
		company: 'Уральские авиалинии',
		image: urals,
		segments: [
			{
				origin: 'Москва',
				originCode: 'DME',
				destination: 'Калининград',
				destinationCode: 'KGD',
				date: '27 мая, сб',
				time: '19:15',
				duration: '2:45',
				dateDest: '27 мая, сб',
				timeDest: '22:45',
			},
			{
				origin: 'Калининград',
				originCode: 'KGD',
				destination: 'Москва',
				destinationCode: 'DME',
				date: '3 июня, сб',
				time: '19:15',
				duration: '2:45',
				dateDest: '3 июня, сб',
				timeDest: '22:45',
			},
		],
	},
	{
		price: '3000',
		company: 'Уральские авиалинии',
		image: urals,
		segments: [
			{
				origin: 'Москва',
				originCode: 'DME',
				destination: 'Калининград',
				destinationCode: 'KGD',
				date: '27 мая, сб',
				time: '19:15',
				duration: '2:45',
				dateDest: '27 мая, сб',
				timeDest: '22:45',
			},
			{
				origin: 'Калининград',
				originCode: 'KGD',
				destination: 'Москва',
				destinationCode: 'DME',
				date: '3 июня, сб',
				time: '19:15',
				duration: '2:45',
				dateDest: '3 июня, сб',
				timeDest: '22:45',
			},
		],
	},
];

const calendarData = [
	{ _id: 1346, date: '25, чт', price: 2000, from: 'moscow', to: 'tver' },
	{ _id: 24555, date: '26, пт', price: 3000, from: 'moscow', to: 'tver' },
	{ _id: 35666, date: '27, сб', price: 3000, from: 'moscow', to: 'tver' },
	{ _id: 456666, date: '28, вс', price: 4780, from: 'moscow', to: 'tver' },
	{ _id: 55543, date: '29, пн', price: 8890, from: 'moscow', to: 'tver' },
	{ _id: 64444, date: '30, вт', price: 9390, from: 'moscow', to: 'tver' },
	{ _id: 7344443, date: '31, ср', price: 8490, from: 'moscow', to: 'tver' },
	{ _id: 83332, date: '1, чт', price: 4490, from: 'moscow', to: 'tver' },
	{ _id: 934344, date: '2, пт', price: 5590, from: 'moscow', to: 'tver' },
	{ _id: 103424, date: '3, сб', price: 6590, from: 'moscow', to: 'tver' },
	{ _id: 11243, date: '4, вс', price: 7590, from: 'moscow', to: 'tver' },
	{ _id: 132433, date: '5, пн', price: 7000, from: 'moscow', to: 'tver' },
	{ _id: 14422, date: '6, вт', price: 3000, from: 'moscow', to: 'tver' },
	{ _id: 14422, date: '7, ср', price: 3000, from: 'moscow', to: 'tver' },
];

export { numberOfTicketsOnPage, ticketsInfo, calendarData };
