name: push
run-name: ${{ github.actor }} push test
on:
  push:
    branches: [front-develop]
  pull_request:
    branches: [front-develop]
jobs:
  tests:
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.JS
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Check build
        run: npm run build
