name: AroundRussia workflow

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd /opt/app-gototravel
            sudo docker-compose down --remove-orphans
            sudo docker-compose rm -f frontend backend
            sudo docker image prune -af
            rm -rf frontend static_folder
            sudo docker-compose pull frontend backend
            sudo docker-compose up -d --build

